channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python =3.8
  - r-base =3.6
  - ipython
  - numpy
  - pandas >=1
  - biopython
  - matplotlib
  - seaborn
  - jedi
  - epc
  - scikit-learn
  - scipy
  - pytest
  - virtualenv
  - parallel
  - emboss
